### ISSUE TITLE
Change header color

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/cli-table#109]
In the readme it says:

> Color/background styling in the header through colors.js

fantastic. but nowhere does it explain how to change the header color? Right now I have a cli table where the header has red text, looking to change it to a different color.

**Comment by ORESoftware** [comment]
I intsalled the typescript typings for cli-table.

```js
const table = new Table({
  colors: false,
  head: ['Name', 'Local Version', 'NPM Registry Version', 'Current Branch', 'Clean?', 'Up-to-Date?', 'Path']
});

```
the typings suggest that "colors" is a boolean argument. Yet false does not turn-off colors in the header.

fml.

but I don't actually want to turn off colors, I just want to change the header color.

**Comment by tecfu** [comment]
Checkout an [example](https://github.com/tecfu/tty-table/blob/master/examples/styles-and-formatting.js) of how to change the header color with [tty-table](github.com/tecfu/tty-table). Its backwards compatible with this package.

**Comment by ORESoftware** [comment]
@tecfu thanks, what do you mean by backward compatible? You mean I can use the example code from cli-table?

Also, this is weird:
https://github.com/tecfu/tty-table/blob/master/examples/styles-and-formatting.js#L7

why wouldn't headerColor be an argument here instead:
https://github.com/tecfu/tty-table/blob/master/examples/styles-and-formatting.js#L70

**Comment by tecfu** [comment]
You can use their API like so:

```
var Table = require('tty-table')('automattic-cli-table');
//now runs with same syntax as Automattic/cli-table
...

**Comment by tecfu** [comment]
> Also, this is weird:
https://github.com/tecfu/tty-table/blob/master/examples/styles-and-formatting.js#L7
why wouldn't headerColor be an argument here instead:
https://github.com/tecfu/tty-table/blob/master/examples/styles-and-formatting.js#L70

You would pass headerColor to the column if you wanted to change it just for that column. 
You would pass headerColor in the options object to change it for all columns. 
You would use both if you didn't wanted to change the default header color for all columns but have one be unique.

**Comment by ORESoftware** [comment]
@tecfu thanks tbh I will probably try out cli-table2 next

**Comment by Paxa** [comment]
Looking at the code (without changing a package):
```js
let table = new Table({
  style: {head: ['green']},
  head: ['apple'],
  ...
});
```

**Comment by chrean** [comment]
If the above solution is accepted, I'd go ahead and close this issue.

**Comment by StreetStrider** [comment]
> Yet false does not turn-off colors in the header.
I second this.
According to code, `colors` option is ignored when it goes to header rendering.

**Comment by StreetStrider** [comment]
Workaround is `style: { head: [ 'reset' ] }`, but I would love to see the fix.
