### ISSUE TITLE
Examples dir is empty

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/cli-table#110]
Looks like this dir hasn't been touched in 5 years:
https://github.com/sorensen/ascii-table/tree/master/example

might be nice to delete it or update it, thx

**Comment by GaryJones** [comment]
@ORESoftware Thanks for posting. 

How is the example directory in that repo, related to this `cli-table` repo?

**Comment by ORESoftware** [comment]
sorry my bad I think I filed this ticket in the wrong repo

**Comment by GaryJones** [comment]
@ORESoftware No problem - please go ahead and close this then :-)

**Comment by ORESoftware** [comment]
ningún problema
