### ISSUE TITLE
Automate using version from package.json

### ISSUE THREAD

**Issue by chrean** [Automattic/cli-table#112]
As discussed in https://github.com/Automattic/cli-table/pull/111 , we should take a step further and automate using version number from package.json instead of `require`ing which is non optimal.

**Comment by LoganDark** [comment]
You could have a simple build process where you rename `lib` to `src` and simply have an NPM script that copies them over and replaces the version number with the correct one.

**Comment by chrean** [comment]
I think we already do something similar for some of our repos, I will look into that.
Thank you for suggestions! 🎉

**Comment by LoganDark** [comment]
Yeah, we could use something simple like `sed`. Nothing complicated.

**Comment by chrean** [comment]
If you want to help with this task, you are welcome. :)

**Comment by LoganDark** [comment]
Sure, I can open another pull request. I actually have an idea of how it'll be done... you'd just need `sed` (for text replacement) and `jq` (for CLI parsing of the package.json). Does that sound like it would be acceptable?

**Comment by chrean** [comment]
Yup, sounds fine to me.

**Comment by LoganDark** [comment]
Alright, I guess I'll be going the CLI route then. I'll create a pull request in a few hours, right now I'm watching a movie :)

**Comment by chrean** [comment]
Not a prio right now, closing.
