### ISSUE TITLE
Test output failed

### ISSUE THREAD

**Issue by ChristianGrieger** [Automattic/cli-table#117]
Hey all,

I included cli-table into my project and tried an output but I get this result. Any idea why it happens?

<img width="645" alt="bildschirmfoto 2018-12-05 um 07 15 48" src="https://user-images.githubusercontent.com/8712219/49493805-be1cb700-f85d-11e8-8ed4-f504ca13b576.png">

Thank you!

**Comment by chrean** [comment]
Hey @ChristianGrieger , I am a bit late but it would help a lot if you could share the code to reproduce the issue. Closing this one as it's very old, please feel free to submit a new issue if you are still stuck and you still need help. :)
