### ISSUE TITLE
Cannot create a text link within a table

### ISSUE THREAD

**Issue by rdotg** [Automattic/cli-table#118]
When trying to create a text link within a table with a package like [terminal-link](https://www.npmjs.com/package/terminal-link) it does not work but strips out the needed formatting.

The call with terminal-link looks like: `terminalLink('My link', 'https://google.com')`. This works in some of the more popular terminals like iTerm and [others](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). Under the hood it does something similar to: `echo -e '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\'` which is what creates the text link.

The image below depicts what the text link should look like on the first line. On the third line however (skip the red hashtag), `cli-table` is formatting it to "90m|".

<img width="53" alt="image" src="https://user-images.githubusercontent.com/20076677/50532098-252e3400-0ac9-11e9-8694-300fed15b2d0.png">

By the way really enjoying this package...thanks for all the great work everyone!

**Comment by m-sureshraj** [comment]
Encountered the same issue on v0.3.1

![image](https://user-images.githubusercontent.com/12813750/54897727-94ac9780-4eef-11e9-8067-e1b3e109939e.png)

Increasing the column width render the link properly but it breaks the table formatting.

![image](https://user-images.githubusercontent.com/12813750/54898124-03d6bb80-4ef1-11e9-9de8-0101a824e267.png)

**Comment by tecfu** [comment]
Links work fine in [tty-table](https://github.com/tecfu/tty-table).

**Comment by alexlee-dev** [comment]
Any update on this issue? Still a problem for me and it's stopping me from using cli-table.

@tecfu above simply put a link to his competitor application which apparently does links ok.
