### ISSUE TITLE
Doesn't work very well with gluegun

### ISSUE THREAD

**Issue by eduardo-ehsc** [Automattic/cli-table#122]
Hi, so I was working in a project with the Gluegun framework (__CLI framework__), searching for ways to display a table in the command prompt, then a installed cli-table, but I dont know what happened and the gluegun somehow got affected and doesn't work in my project anymore, so I had to undo some commits.

Please fix this error, it would be nice to use this dependency with Gluegun framework.

**Comment by chrean** [comment]
Hi @eduardo-ehsc , would be awesome if you could add some informations on what error(s) you are seeing, how to reproduce, etc.
