### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by ready-research** [Automattic/cli-table#141]
Hi @chrean @rauchg I have opened a PR which will fix the security issue Prototype Pollution. Please have a look at it. If you are fine with it please comment `@huntr-helper - LGTM`
If you need any changes please comment on this PR. Thanks.
Ref: https://github.com/418sec/cli-table/pull/1

**Comment by chrean** [comment]
Hi @ready-research , woiuld be helpful if you could create a PR against this repo instead of your personal fork, please.
Thanks for the contribution!

**Comment by ready-research** [comment]
Hi @chrean, Thanks for the quick response. 

Can you please comment on https://github.com/418sec/cli-table/pull/1 with `@huntr-helper - LGTM`, it will automatically open a PR in this repository to merge. It's a process in huntr, instead of opening a direct PR in the repository, we will ask maintainers to discuss whether they are fine with it or need any changes(to reducing the mess in the original repository). Thanks again.

**Comment by ready-research** [comment]
Closing this with https://github.com/Automattic/cli-table/pull/142
