### ISSUE TITLE
0.3.7 crashes when creating tables without options

### ISSUE THREAD

**Issue by DavidOStewart** [Automattic/cli-table#153]
https://github.com/Automattic/cli-table/blob/master/lib/index.js#L51

`if (options.rows)` throws when options is undefined, which happens occurs when creating a table with an empty constructor:

 `const table = new Table()`.

Pin version to 0.3.6 to retain original functionality.

**Comment by phess101** [comment]
Thanks for this! I just stumbled across this error as well! I created a PR to resolve it https://github.com/Automattic/cli-table/pull/154

**Comment by dwolverton** [comment]
+1 This is should be high priority. Firebase CLI uses this with undefined options, and it entirely prevents the emulator (pretty much used for any development with Firebase) from starting.

The error looks like this, for those searching...
```
[debug] [2021-11-18T02:13:23.958Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (/Users/___/.npm-global/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
    at Command.actionFn (/Users/___/.npm-global/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
