### ISSUE TITLE
0.3.7 node version

### ISSUE THREAD

**Issue by dguettler** [Automattic/cli-table#156]
Hi, is there a reason to restrict node to >= 12.

Looks like ember-cli has cli-table as a dependency of dependencies and it's trying to install the latest version. However the ember-cli version in use uses node 10. Therefor installing cli-table is failing.
So I'm wondering if that requirement could be changed.

Thank you

**Comment by NicholasNoise** [comment]
Please unlist 0.3.7 version.

**Comment by josantana** [comment]
It should not be a patch/minor. Please unlist 0.3.8 and 0.3.7.
