### ISSUE TITLE
v0.3.7 has a breaking change

### ISSUE THREAD

**Issue by ljharb** [Automattic/cli-table#160]
v0.3.7 has a breaking change - it adds strip-ansi v6, which breaks support for node < 12.

This should have been v0.4.0 instead, since v0.3.6 declares an `engines` of `{ node: '>= 0.2.0' }`. Also, changing "engines" to make previously valid things invalid is also a breaking change, which v0.3.7 did as well.

Can you please publish a v0.3.x version that reverts that change, and then feel free to republish v0.4.0 with the breaking change?

**Comment by chrean** [comment]
I guess we won't make any further changes to 0.3.x line. Node and packages it supports are too old and discontinued, and so should 0.3.x be marked as: old and discontinued.

**Comment by ljharb** [comment]
That’s a reasonable position to take, but v0.3.7 still need to be capped off with a v0.3 release that restores old node support.

**Comment by ljharb** [comment]
A perhaps easy alternative is republishing v0.3.6 as v0.3.latest, and then publishing the actual latest as v0.4.0?

**Comment by chrean** [comment]
> A perhaps easy alternative is republishing v0.3.6 as v0.3.latest, and then publishing the actual latest as v0.4.0?

That's exactly what I am doing.
Making any changes on top of 0.3.6 is causing lots of issues and it is not worth all the hassle.
It is simply not realistic, add features or fixes based on newer versions of Node and/or dependencies to the 0.3x line, which supports ancient releases.

**Comment by chrean** [comment]
Released v0.3.10 which reverts all changes to v0.3.6.
All future changes will go into 0.4.x series.

**Comment by michaelarnauts** [comment]
@chrean thanks for looking into this.
However, it seems v0.3.10 still shows a dependancy on strip-ansi, pinning to v0.3.6 works.

```
# sudo npm install -g cli-table@0.3.6

changed 2 packages, and audited 3 packages in 551ms

found 0 vulnerabilities
# bpmnlint --version
7.4.0
# sudo npm install -g cli-table@0.3.10

changed 2 packages, and audited 3 packages in 562ms

found 0 vulnerabilities
# bpmnlint --version                  
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'strip-ansi'
Require stack:
- /usr/lib/node_modules/cli-table/lib/utils.js
- /usr/lib/node_modules/cli-table/lib/index.js
- /usr/lib/node_modules/bpmnlint/bin/bpmnlint.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/cli-table/lib/utils.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/cli-table/lib/utils.js',
    '/usr/lib/node_modules/cli-table/lib/index.js',
    '/usr/lib/node_modules/bpmnlint/bin/bpmnlint.js'
  ]
}
```

**Comment by ljharb** [comment]
https://unpkg.com/cli-table@0.3.10/package.json seems like it should work fine; I’ll revert the pinning in https://github.com/tbranyen/salita/commit/68abf80fb8ac1aed0925af05122325fcda67c60f and confirm.

@michaelarnauts that error comes from “bnpmlint”, which seems like something you alone are running?

**Comment by chrean** [comment]
@michaelarnauts is right. 
There is a stale `require` to `strip-ansi`.

Going to fix it.
Yes, today it's one of those days. Sorry about this, folks.

**Comment by chrean** [comment]
0.3.11 is out, I have deleted all references to `strip-ansi`. 🙇

**Comment by michaelarnauts** [comment]
> @michaelarnauts is right. There is a stale `require` to `strip-ansi`.
> 
> Going to fix it. Yes, today it's one of those days. Sorry about this, folks.

No worries, you are doing awesome work!
