### ISSUE TITLE
Auto text wrap support?

### ISSUE THREAD

**Issue by stevenvachon** [Automattic/cli-table#35]
Would be sweet.

**Comment by xavierchou** [comment]
+1

**Comment by gajus** [comment]
+1

**Comment by tecfu** [comment]
I submitted a patch for this that renders tables fully responsive. 
https://github.com/Automattic/cli-table/pull/59

Unit tests fail, however, because the hardcoded tests strings don't match to the responsive output.

**Comment by brycepj** [comment]
+1

**Comment by tecfu** [comment]
Support for automatic text wrapping has been added in the following fork:

https://github.com/tecfu/cli-table

**Comment by tecfu** [comment]
Also, since pull requests are being ignored here and I found the code unmaintainable I created an alternative that supports automatic line wrapping with colors, padding, alignment, and callbacks.

https://github.com/tecfu/tec-table
