### ISSUE TITLE
option to disable terminal coloring

### ISSUE THREAD

**Issue by nherment** [Automattic/cli-table#39]
Colors are nice but don't render well when used with automated systems and passed through non-terminal interface.

For example, during a build the generated table could end up in a text email or on a HTML field that does not parse colors.

**Comment by raine** [comment]
You could also use a module like [strip-ansi](https://www.npmjs.com/package/strip-ansi)

**Comment by stevenvachon** [comment]
colors.js has a `stripColor()` https://github.com/Marak/colors.js/blob/master/lib/colors.js#L45-L47

**Comment by YouTwitFaceTG** [comment]
@stevenvachon seems it changed and is now https://github.com/Marak/colors.js/blob/master/lib/colors.js#L55-L57

**Comment by stevenvachon** [comment]
@YouTwitFaceTG It doesn't matter now that there's [table](https://npmjs.com/table)
