### ISSUE TITLE
Always ignore color for column width calculation

### ISSUE THREAD

**Issue by mike-spainhower** [Automattic/cli-table#41]
Even though `strlen` tries to account for terminal coloring (https://github.com/LearnBoost/cli-table/blob/master/lib/cli-table/utils.js#L79), it seems whenever I use `chalk.cyan('string')` cli-table treats the non-displaying color chars as real chars for the purposes of `colWidths`.  Whatever is particular about `chalk.cyan` needs to be ignored for width calculations.

**Comment by jamestalmage** [comment]
[cli-table2][https://github.com/jamestalmage/cli-table2] does what you are looking for

**Comment by SpainTrain** [comment]
Awesome, thanks for the heads up!  I assume this project has been abandoned `V_V`
