### ISSUE TITLE
column (and row?) spanning

### ISSUE THREAD

**Issue by stevenvachon** [Automattic/cli-table#51]
I'm trying to figure out how to best approach this.

I've been thinking about adding an `autoColSpan` that auto-spans columns to fit the total number of columns in the table:

``` js
var table = new Table({ autoColSpan:true });
table.push(
    [ ["column"] ],    // stretches to fit 2 columns
    [ ["column"], ["column"] ]
);
```

While the above allows for overall simple list-based tables, it does not allow for individual control or rowspan.

Another approach is to do something similar to #42 with per-column config:

``` js
var table = new Table();
table.push(
    [ {content:"column", colSpan:3} ],
    [ ["column"], {content:"column", colSpan:2} ],
    [ ["column"], ["column"], ["column"] ]
);
```

which can also be applied to a rowspan:

``` js
var table = new Table();
table.push(
    [ ["column"], ["column"], {content:"column", rowSpan:2} ],
    [ ["column"], ["column"] ],
    [ ["column"], ["column"], ["column"] ]
);
```

Other per-column settings can be added as well, such as `align` (to override `options.colAligns`), etc.

**Comment by stevenvachon** [comment]
@jamestalmage awesome. I'll have to try it out soon.

@rauchg what do you think about accepting the rewrite?

**Comment by rauchg** [comment]
As long as the tests pass, I'd be glad to review a PR

**Comment by stevenvachon** [comment]
@jamestalmage would you be interested in making a PR with your rewrite?

**Comment by jamestalmage** [comment]
It does pass the tests, and I'd be happy to submit as a PR. A couple potential problems though:

  1. I used mocha + chai for tests (I had to convert the original test suite). Currently my dependencies prevent supportting Node 0.6 or 0.8. I am not sure if earlier versions of those dependencies would allow for earlier versions of Node or not.
  2. I'd bet the current implementation is faster than mine. At least some of the slowdown is necessary as computing the layout is not trivial.
  3. It's a complete rewrite. So you'd be taking on maintaining a lot of my fugly code. Heaven help you ;).

How about you look over my code (jamestalmage/cli-table2) and tell me if you are still interested.

**Comment by stevenvachon** [comment]
@rauchg ^

I might be able to find some time in a few months to clean it up if it needs it. I have a few other side projects that are currently taking priority.

**Comment by rauchg** [comment]
np

**Comment by jamestalmage** [comment]
There are two tests that I modified:
  * [the first](https://github.com/jamestalmage/cli-table2/blob/master/test/original-cli-table-index-tests.js#L114) is a side-effect of rendering borders cell-by-cell. My implementation has some extra on/off color toggles in the border string - it should not impact the onscreen appearance.
  * [the second](https://github.com/jamestalmage/cli-table2/blob/master/test/original-cli-table-index-tests.js#L276) was an intentional departure from the current behavior. The way string length is currently determined for `null` and `undefined` didn't make a lot of sense to me.
