### ISSUE TITLE
Column width miss-calculated for CJK characters

### ISSUE THREAD

**Issue by pm5** [Automattic/cli-table#62]
It appears that columns widths are calculated and aligned based on string length of content, ignoring the fact that some characters, such as CJK, are double-width.

Here is an example showing where the precision is off:

![screen shot 2015-04-05 at 11 06 38](https://cloud.githubusercontent.com/assets/119645/6995584/25542d54-db84-11e4-98d4-55630062097d.png)

**Comment by xixilive** [comment]
```
exports.strlen = function(str){}
```

https://github.com/Automattic/cli-table/blob/master/lib/utils.js#L79

**Comment by xixilive** [comment]
you can use this fork currently

https://github.com/xixilive/cli-table

**Comment by heycalmdown** [comment]
+1

**Comment by heycalmdown** [comment]
@rauchg accept this PR plz

https://github.com/xixilive/cli-table/commit/ea9fe609a20e560aea089f9b0044669dbc9ff397

**Comment by Rykka** [comment]
exactly!

**Comment by ahkimkoo** [comment]
中文字长度不对的问题，我改了一个，重新发布模块为cli-table-ext
https://github.com/ahkimkoo/cli-table

**Comment by tecfu** [comment]
Or you can use [tty-table](https://github.com/tecfu/tty-table), which is backwards compatible with this syntax but adds features.
