### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by eGavr** [Automattic/cli-table#64]
Hi! Thank you very much, very useful tool.

But I was confused about how to align the data in cells and rows, for example by center (I've read in README that it is possible, but I did not find how).

**Comment by tecfu** [comment]
Like so:

```
    var table = new Table({
        head: ['Rel', 'Change', 'By', 'When']
      , style: {
            'padding-left': 1
          , 'padding-right': 1
          , head: []
          , border: []
        }
      , colWidths: [6, 21, 25, 17]
    });
```

And for a better terminal table option, I suggest tty-table - even though it isn't massively starred.

https://github.com/tecfu/tty-table

**Comment by tecfu** [comment]
I suggest using a different package for alignment support. 

My package, tty-table allows you to specify the alignment for both column headers and values - separately if desired. 

https://github.com/tecfu/tty-table

**Comment by jamestalmage** [comment]
Also see [cli-table2](https://github.com/jamestalmage/cli-table2), it's 100% API compatible with this library.

**Comment by jacksondc** [comment]
Why is text alignment on the list of features if it isn't supported?
