### ISSUE TITLE
Chokes on null values

### ISSUE THREAD

**Issue by veltman** [Automattic/cli-table#65]
A cell containing `null` as the value throws an error (`TypeError: Cannot read property 'toString' of null`).  I'm not sure whether a more sensible default would be to stringify it to an empty string or to the string `null` but it seems like either would be preferable to an error.

**Comment by raine** [comment]
stringifying to null makes sense

**Comment by raine** [comment]
doh. this is already fixed but not released on npm.

and it uses empty strings, i'd much prefer "null"

**Comment by ijse** [comment]
It seems that still not released on npm.

**Comment by tecfu** [comment]
[tty-table](https://www.github.com/tecfu/tty-table) handles null values out of the box. It also has a [drop-in adapter automattic/cli-table](https://github.com/tecfu/tty-table/blob/master/docs/automattic-cli-table.md).

```
var table = new Table({
	defaultValue : 0,
	errorOnNull : false,
	head: ['Rel', 'Change', 'By', 'When'],
	colWidths: [6, 21, 25, 17]
});
table.push(
 ['v0.1', , 'rauchg@gmail.com', '7 minutes ago']
, ['v0.1', null, 'rauchg@gmail.com', '8 minutes ago']
);
console.log(table.toString());
```

**Comment by robogeek** [comment]
Hurm... I'm seeing the same behavior.. am not using cli-table directly because it's used in csvwriter.

In any case, I have an object:

```
System {
    _id: 44,
    _module_quan: 504,
    _total_kw: 128.52,
    _meter_id: 'TBD',
    _longitude: 0,
    _latitude: 0,
    _projects_id: 23,
    _devices: undefined } 
```

Notice the field with the undefined value.

I put a couple print statements in the cli-table source, and got this output showing it bombs on `undefined.toString()`

```
[ 1, 44, 504, 128.52, 'TBD', 0, 0, 23, undefined ]
1
44
504
128.52
'TBD'
0
0
23
undefined
TypeError: Cannot read property 'toString' of undefined
    at /Users/david/bin/node_modules/cli-table/lib/index.js:186:26
    at Array.forEach (native)
    at generateRow (/Users/david/bin/node_modules/cli-table/lib/index.js:184:11)
    at /Users/david/bin/node_modules/cli-table/lib/index.js:279:16
    at Table.forEach (native)
    at Table.toString (/Users/david/bin/node_modules/cli-table/lib/index.js:262:10)
    at createCLITable (/Users/david/bin/node_modules/csvwriter/lib/csvwriter.js:164:18)
    at csvwriter (/Users/david/bin/node_modules/csvwriter/lib/csvwriter.js:108:9)
    at Promise (/Users/david/bin/node_modules/xlsetup/cli.js:700:13)
    at filterOutput (/Users/david/bin/node_modules/xlsetup/cli.js:698:16)
```

**Comment by robogeek** [comment]
BTW - that this has been an open issue for a year and a half is troublesome

**Comment by JulienPalard** [comment]
Two year birthday for this issue! Just got bitten (using null as a default value of a pm2 module…).

**Comment by TamimiGitHub** [comment]
This is still not published on npm. Any plans?

**Comment by TamimiGitHub** [comment]
Thanks @tecfu this looks better - will try it out and contribute

**Comment by adadgio** [comment]
Still having the issue ! ... :p

**Comment by panlina** [comment]
Still an issue in 2020. Seems this library is abandoned.
@raine are you going to take any action on this library?

**Comment by raine** [comment]
No. Use an alternative that is not abandoned.

**Comment by chrean** [comment]
Better late than ever, maybe, but a new version has just been released.
