### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by raine** [Automattic/cli-table#69]

**Comment by GaryJones** [comment]
While a new version is definitely warranted, after some fixes, I don't think opening a separate issue with just a title is going to convince the maintainers to do it :-)

**Comment by harrysarson** [comment]
I published: https://www.npmjs.com/package/@harrysarson/cli-table so I could use the package as is. :)

**Comment by chrean** [comment]
Well a new version has been published, so closing this one. :)
