### ISSUE TITLE
undefined/null values are printed as very wide

### ISSUE THREAD

**Issue by raine** [Automattic/cli-table#70]
```js
var Table = require('cli-table')
var table = new Table({
  head: ['a', 'b']
})

table.push(
  ['foo', 'bar'],
  ['xyz', undefined]
)

console.log(table.toString())
```

```
┌─────┬───────────┐
│ a   │ b         │
├─────┼───────────┤
│ foo │ bar       │
├─────┼───────────┤
│ xyz │           │
└─────┴───────────┘
```

I wonder what the rationale here was,

https://github.com/Automattic/cli-table/commit/fe6cbc199fdabcf3c31acb6f63c75cd1ccb1954c

**Comment by stevenvachon** [comment]
```js
console.log(typeof undefined); //-> "undefined"
```

**Comment by stevenvachon** [comment]
Err, sorry, this: [utils.js#L81](https://github.com/Automattic/cli-table/blob/fe6cbc199fdabcf3c31acb6f63c75cd1ccb1954c/lib/cli-table/utils.js#L81)

```js
console.log("" + undefined); //-> "undefined"
```

**Comment by raine** [comment]
So a fix could be?

```diff
-  var stripped = ("" + str).replace(code,'');
+  var stripped = ("" + (str == null ? '' : str)).replace(code,'');
```

**Comment by stevenvachon** [comment]
A micro-optimization might be `(str != null ? str : '')`, but yeah, looks good to me.

**Comment by jamestalmage** [comment]
check out [cli-table2], it is 100% API compatible with this library and passes the test suite from this codebase with [one exception directly related to this issue][undefined-formatting]. There are additional benefits as well, read the docs for more info.

[cli-table2]:https://github.com/jamestalmage/cli-table2
[undefined-formatting]:https://github.com/jamestalmage/cli-table2/blob/master/test/original-cli-table-index-tests.js#L276
