### ISSUE TITLE
Install cli-table is failed.

### ISSUE THREAD

**Issue by puritys** [Automattic/cli-table#72]
Error message:
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "cli-table" "--save"
npm ERR! node v0.12.1
npm ERR! npm  v2.11.1

npm ERR! shasum check failed for /tmp/npm-5519-25fd97d9/registry.npmjs.org/colors/-/colors-1.0.3.tgz
npm ERR! Expected: 0433f44d809680fdeb60ed260f1b0c262e82a40b
npm ERR! Actual:   5996ece2af528700f64e9794429fe8a7a594fd14
npm ERR! From:     https://registry.npmjs.org/colors/-/colors-1.0.3.tgz

**Comment by SidBala** [comment]
Hitting same issue.
