### ISSUE TITLE
Option to turn off colors

### ISSUE THREAD

**Issue by chrisvfritz** [Automattic/cli-table#74]
I'd love an option to turn off colors. I'd like to use this for the hubot of a Slack channel, but the colorization seems extremely resistant to removal. I've tried all of these:
- `/(\x03\d{0,2}(,\d{0,2})?|\u200B)/g`
- `/[\x0F\x02\x16\x1F]/g`
- `/\x1b\[.\{1,5\}m/g`

But I still see `[90m`, `[39m`, `[31m`, etc throughout the table. :confused:

**Comment by chrisvfritz** [comment]
Seems like `--no-color` seems to work, though that disables color for all log output, rather than the table sent to Slack.

**Comment by tecfu** [comment]
This project doesn't seem to be maintained anymore, in spite of its popularity. 

I've written a similar utility that allows you to control colors on a more granular level. 
See: https://github.com/tecfu/tty-table

**Comment by chrisvfritz** [comment]
Thanks for pointing this out! I'll check it out.

**Comment by rafaelrinaldi** [comment]
:+1: for this. `cli-table` is a dependency of a module I'm running on PhantomJS's context and `colors.js` is complaining about not having `process` available. I had to remove `cli-table` because of that.

**Comment by jamestalmage** [comment]
If you are just looking to have colors not screw up your table, the [cli-table2]:[cli-table2].
It's 100% API compatible with this library, and passes the entire unit test suite (with the exception of a single formatting test that I felt formatted the text incorrectly).
In addition to handling colors, it also has some [additional features][cell-spanning] including vertical/horizontal cell-spanning.

[cli-table2]: github.com/jamestalmage/cli-table2
[cell-spanning]: https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md

**Comment by jamestalmage** [comment]
@rafaelrinaldi 
[cli-table2] also offers a means of [disabling colors], if that is what you need.


[cli-table2]:https://github.com/Automattic/cli-table/issues/github.com/jamestalmage/cli-table2
[disabling colors]:https://github.com/jamestalmage/cli-table2/blob/master/basic-usage.md#basic-usage---disable-colors---used-often-in-the-examples-and-tests

**Comment by rafaelrinaldi** [comment]
@jamestalmage That's interesting, thanks for pointing out. Let's hear what the maintainers of this project has to say...
In the meantime I will give `cli-table2` a try :)

**Comment by nodesocket** [comment]
This works:

````
var tableOptions = {};
if(ARGS.nocolors) {
    tableOptions = {
        style: {
            head: [],
            border: []
        }
    }
}
var t = new table(tableOptions);
````

**Comment by seriousManual** [comment]
@jamestalmage thanks for pointing out the 'no-color' option at cli-table2!

**Comment by joshbetz** [comment]
#95 should fix it
