### ISSUE TITLE
table display not right in window8 and linux

### ISSUE THREAD

**Issue by zhangtao07** [Automattic/cli-table#77]
whatever in windows or linux ,the table is not right.

![baiduhi_2015-8-14_16-44-22](https://cloud.githubusercontent.com/assets/4675923/9270425/4f871078-42a4-11e5-9c5b-06159e0d6847.png)

and Horizontal Tables is totally crash:

![image](https://cloud.githubusercontent.com/assets/4675923/9270437/6b8826c2-42a4-11e5-9a59-a337f1d6de4b.png)

**Comment by fritx** [comment]
+1 for this.. not work in Windows (win7)

![image](https://cloud.githubusercontent.com/assets/6647633/9752396/233f6c8e-56e2-11e5-8e16-89a35aeb4b01.png)

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/13834616/6d6cc87c-ec2b-11e5-991b-8d780f08d022.png)

```js
chars: {
          'top': ' '
        , 'top-mid': ' '
        , 'top-left': ' '
        , 'top-right': ' '
        , //...
      }
```

**Comment by jacobbogers** [comment]
Why is this an issue for windows? can someone comment, can this be fixed??
