### ISSUE TITLE
Support streaming results / incrementally adding rows

### ISSUE THREAD

**Issue by glennblock** [Automattic/cli-table#78]
I am using cli-table in my new splunkrepl cli (https://www.npmjs.com/package/splunkrepl). One of the things popular in the Splunk world is streaming results, and some of those results display in tables. It would be nice to be able to output the results as they come in, ie progressively rendering the table as currently I wait until all results are in before I render.

If this is doable today, I'd be happy to just use that approach.

**Comment by ewnd9** [comment]
Did you consider something like below?

```javascript
stream.on('data', function(data) {
  table.push(data);
  var curr = table.toString().split('\n');
  console.log(curr.slice(prev.length, curr.length).join('\n'));
  prev = curr;
});

**Comment by gajus** [comment]
@ewnd9 approach seems correct. In addition, consider using something like https://github.com/trentm/node-bunyan, which is designed for handling streams (although output is not in a tabular format).

**Comment by glennblock** [comment]
You think splitting a large table over and over is a good solution? That
seems pretty expensive especially for a large table.

**Comment by glennblock** [comment]
Thanks for the tip regardless :-)

**Comment by ewnd9** [comment]
@glennblock hard to say without benchmarks. You could always implement something like table rotation on every n-th chunk of stream in case of low perfomance

**Comment by gajus** [comment]
Sorry, I have actually misread the example. You don't need to render the entire table every time. A lot simpler would be to simply render a single row. I am sure cli-table or cli-table2 supports that. If not, have a look at https://www.npmjs.com/package/table.

**Comment by glennblock** [comment]
@ewnd9 yeah I am just imagining the scenario where one is streaming tons and tons of events. It seems completely wasteful and slow to have an infinitely growing / continually string concatenated table.
