### ISSUE TITLE
Consider deprecating in favour of "table" package

### ISSUE THREAD

**Issue by gajus** [Automattic/cli-table#79]
I have written a library for displaying data in a table.

https://github.com/gajus/table

This package implements all features of `cli-table` and addresses some of the open issues:
- https://github.com/Automattic/cli-table/issues/35
- https://github.com/Automattic/cli-table/issues/8
- https://github.com/Automattic/cli-table/issues/10
- https://github.com/Automattic/cli-table/issues/64

Consider [deprecating](https://docs.npmjs.com/cli/deprecate) `cli-table` in favour of `table` package.

The reason I choose to write a library from the ground up is because I am building something that will heavily rely on text tables and neither of the implementations (ascii-table, cli-table or text-table) met my requirements. I have looked at all the source codes. ascii-table package had the best API, but I did not feel comfortable working with a codebase using prototype inheritance, no separation of logic and minimal test coverage.

I have put a lot of thinking into how to make table package modular, easy to test, easy to contribute to and easy to extend for different use cases.

**Comment by stevenvachon** [comment]
Cool. Does it also have truncation like cli-table?

**Comment by gajus** [comment]
@stephanethomas I cannot see the definition of "truncation" in the docs beyond brief statement in the "features" section ("Text truncation based on predefined widths"). If thats a generic truncation of a string in a column, then that falls outside of the "table" formation scope. I suggest you to use a utility function to format data before passing to the table, e.g. [`_.trunc`](https://lodash.com/docs#trunc) in combination with [`_.map`](https://lodash.com/docs#map)

That said, `table` library supports smart content wrapping (column `maxWidth` property).

**Comment by stevenvachon** [comment]
truncation with ellipsis: "this is a long sentence" would become "this is a…"

**Comment by gajus** [comment]
Do you it is the responsibility of the table formation library to truncate the data?

**Comment by stevenvachon** [comment]
Not necessarily, but it is convenient and creates would have familiarity with cli-table.

**Comment by jamestalmage** [comment]
http://github.com/jamestalmage/cli-table2 does [truncation](https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md#multi-line-content-will-flow-across-rows-in-rowspan-cells---complex-layout).


Also has [colspan](https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md#use-colspan-to-span-columns---colspan-below-normal-cell) and [rowspan](https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md#use-colspan-to-span-columns---colspan-below-normal-cell), layouts can be as [complex as you want](https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md#multi-line-content-will-flow-across-rows-in-rowspan-cells---complex-layout).

**Comment by gajus** [comment]
@jamestalmage cli-table2 is quite nice. If I had known about it, I'd probably skipped developing `table` altogether.

I am thinking I pushed `table` logic a notch too far. Having static column widths (as in `cli-table` and `cli-table2`) makes the code logic considerably less complicated. Supporting colspan and rowspan using dynamic widths wouldn't be easy.

**Comment by jamestalmage** [comment]
@gajus Thank you! 

Sorry I haven't promoted it better :disappointed: 

I do [make an attempt](
https://github.com/jamestalmage/cli-table2/blob/master/advanced-usage.md#a-column-with-a-null-column-width-will-be-automatically-widened-to-fit-content) to support dynamic widths, but it is limited. There is no way to set which column takes priority if there is contention for screen width, nor a way to set a minimum for a dynamic row.

**Comment by stevenvachon** [comment]
cli-table2 needs to be cleaned up, though ;) you had said it yourself, @jameskoster

**Comment by gajus** [comment]
@stevenvachon Please create an issue on https://github.com/gajus/table regarding the ability to truncate content. I will update README.md to reflect the requirement.

**Comment by jamestalmage** [comment]
@stevenvachon 
There are [improvements I want to make](https://github.com/jamestalmage/cli-table2/issues/3), and I mentioned a [few issues](https://github.com/Automattic/cli-table/issues/51#issuecomment-69876817) that prevent completely deprecating this implementation for mine. I have never said "it needs to be cleaned up", or that it was not production ready. It has 100% test coverage, and fixes issues that have gone without resolution here for years. Most importantly, users who post to issues to `cli-table2` have seen drastically faster response.

Here is the complete list of open `cli-table` issues which `cli-table2` resolves:

* #2 
* #8 
* #30
* #35
* #41
* #51
* #64
* #74

**Comment by stevenvachon** [comment]
All I know regarding code cleanliness is that https://github.com/Automattic/cli-table/issues/51#issuecomment-69876817 contains
> you'd be taking on maintaining a lot of my fugly code. Heaven help you ;)

**Comment by gajus** [comment]
V3 released:

* Added [text truncation](https://github.com/gajus/table#table-usage-text-truncation) as requested by @stevenvachon.
* Added documentation about [text wrapping](https://github.com/gajus/table#table-usage-text-wrapping).
* Removed minWidth, maxWidth properties in favour of a single property width.
* Added style for [borderless table](https://github.com/gajus/table#borderless-table).
* Added [`drawJoin`](https://github.com/gajus/table#table-usage-draw-join) callback that controls whether a specific joining/separating row is drawn.
* Added `columnDefault` configuration property that sets default column properties that can be overwritten for each individual column.

**Comment by gajus** [comment]
Implemented streaming.

https://github.com/gajus/table#table-usage-streaming

**Comment by stevenvachon** [comment]
Wow, that streaming gif is enticing.

**Comment by gajus** [comment]
Implemented [word wrapping](https://www.npmjs.com/package/table#table-usage-text-wrapping), e.g.

Without `wrapWord`:

```
╔══════════════════════╗
║ Lorem ipsum dolor si ║
║ t amet, consectetur  ║
║ adipiscing elit. Pha ║
║ sellus pulvinar nibh ║
║ sed mauris convallis ║
║ dapibus. Nunc venena ║
║ tis tempus nulla sit ║
║ amet viverra.        ║
╚══════════════════════╝
```

with `wrapWord`:

```
╔══════════════════════╗
║ Lorem ipsum dolor    ║
║ sit amet,            ║
║ consectetur          ║
║ adipiscing elit.     ║
║ Phasellus pulvinar   ║
║ nibh sed mauris      ║
║ convallis dapibus.   ║
║ Nunc venenatis       ║
║ tempus nulla sit     ║
║ amet viverra.        ║
╚══════════════════════╝
```

**Comment by stevenvachon** [comment]
Hypenated? :) awesome work

**Comment by stevenvachon** [comment]
Hypenated? :) awesome work

**Comment by ORESoftware** [comment]
Does it have multi-line rows? Looking for that feature in an ascii/unicode table now...

**Comment by tecfu** [comment]
@ORESoftware 

[tty-table](https://www.github.com/tecfu/tty-table) handles multi-line rows out of the box. It also has a [drop-in adapter automattic/cli-table](https://github.com/tecfu/tty-table/blob/master/docs/automattic-cli-table.md).

```
var Table = require('tty-table/automattic-cli-table');

...
```

![tty table](https://cloud.githubusercontent.com/assets/7478359/15693270/c901a0ce-2748-11e6-8fcb-e946b6c608f1.png "tty-table")

**Comment by gajus** [comment]
How exactly is this better than "table" package?
