### ISSUE TITLE
Table doesn't display well in Windows cmd

### ISSUE THREAD

**Issue by goorockey** [Automattic/cli-table#81]
![cli-table](https://cloud.githubusercontent.com/assets/1220971/11887687/981d65e6-a571-11e5-8a09-55142e7812aa.png)

The columns don't align well because of the difference width of space and '─'.

**Comment by runemadsen** [comment]
I'm getting the following by copy/pasting the example code on 10.10.5 and node 4.2.0:

![screen shot 2016-01-07 at 11 26 40 am](https://cloud.githubusercontent.com/assets/192021/12168312/9d42cf3c-b531-11e5-8fd3-987e23a18b04.png)

**Comment by fritx** [comment]
same prob: #77

**Comment by jacobbogers** [comment]
Will this be fixed??
