### ISSUE TITLE
Any strategy for handle other languages displays?

### ISSUE THREAD

**Issue by magicdawn** [Automattic/cli-table#82]
e.g Simplified Chinese (as 简体中文)

![image](https://cloud.githubusercontent.com/assets/4067115/12375706/8d66d62c-bd0a-11e5-9307-76cd7f0b6edd.png)

And for simplified chinese, test with unicode `\u4E00－\u9FA5`, should double the length, then it will display well.

``` js
strlen('你好world') => 2*2 + 5 = 9
```

BTW, I'm using the [Hack](https://github.com/chrissimpkins/Hack) Font for display.

**Comment by magicdawn** [comment]
After https://github.com/magicdawn/cli-table/commit/65d1857e82df461dfaffaf611f19133a46c74425 it displays well for chinese. but what about other languages ?

**Comment by magicdawn** [comment]
Time flies and Problems remains 😂

**Comment by zhangqingyv** [comment]
same problem

<img width="568" alt="qq20161125-0 2x" src="https://cloud.githubusercontent.com/assets/6878741/20615793/02551bde-b318-11e6-9394-6a364d504d1a.png">

**Comment by magicdawn** [comment]
I have a PR at #92, but looks like the project is not maintained any more, see package.json deps, 
the mocha's old name expressso list there :joy

**Comment by tecfu** [comment]
Use [tty-table](https://www.github.com/tefu/tty-table) instead. It has built-in support for unicode characters.
