### ISSUE TITLE
Add support for working with pipes.

### ISSUE THREAD

**Issue by elfet** [Automattic/cli-table#84]
From cli:

```
$ pbpaste | cli-table --csv | pbcopy
```

**Comment by tecfu** [comment]
You can do this with [tecfu/tty-table](https://github.com/tecfu/tty-table). 

Try:

```
npm i -g tty-table
$ pbpaste | tty-table --format=csv | pbcopy
```

Docs [here](https://github.com/tecfu/tty-table/blob/master/docs/terminal.md). 

You can also view a continuous stream in the terminal with tty-table, using:

```
somestream | tty-table 
```
![terminal-streaming](https://cloud.githubusercontent.com/assets/7478359/15693685/15354268-274c-11e6-9fe4-0b97ce57e46a.gif)
