### ISSUE TITLE
is cli-table still maintained?

### ISSUE THREAD

**Issue by thisconnect** [Automattic/cli-table#91]

**Comment by BitwiseGuy** [comment]
It doesn't appear so. The documentation is terrible.

**Comment by felquis** [comment]
@automattic-challenges how can I use?

**Comment by felquis** [comment]
Fixed my comment, how can I help

**Comment by thisconnect** [comment]
btw automattic is not automattic-challenges, automattic is an org

**Comment by roccomuso** [comment]
+1

**Comment by tecfu** [comment]
I've written a backwards compatible package called <a href="https://github.com/tecfu/tty-table">tty-table</a>. It has all the features that cli-table does and can even use the same API with an adapter. 

Plus its maintained.

**Comment by zoltan-nz** [comment]
An actively maintained successor: [cli-table](https://github.com/jamestalmage/cli-table2) 2
