### ISSUE TITLE
unicode string format error, eg: chinese character

### ISSUE THREAD

**Issue by sabakugaara** [Automattic/cli-table#96]
Maybe should `wcwidth`, not `string length` to calculate padding

**Comment by sabakugaara** [comment]
PR: https://github.com/Automattic/cli-table/pull/97

**Comment by orangeyyy** [comment]
this problem is worth to fix

**Comment by sabakugaara** [comment]
seems, repo is not maintained

**Comment by tecfu** [comment]
github.com/tecfu/tty-table has support for Chinese characters.
