### ISSUE TITLE
default border color not visible on PuTTY

### ISSUE THREAD

**Issue by irbrad** [Automattic/cli-table#98]
The default border color (grey) does not show on PuTTY since it uses the same color as the background color in the terminal emulator.  

Before:
![image](https://cloud.githubusercontent.com/assets/1220715/23757150/00257834-04b4-11e7-998f-4069cb4de9c2.png)

After:
![image](https://cloud.githubusercontent.com/assets/1220715/23757173/0ef1bf80-04b4-11e7-8e50-35a9009520b0.png)

**Comment by tecfu** [comment]
You can set custom colors using tecfu/tty-table and still retain the automattic/cli-table API if you wish.

**Comment by chrean** [comment]
Fixed with: https://github.com/Automattic/cli-table/pull/99 .

A color theme switch would be preferred, though.
